version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql-prod
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lab1

  spring_app:
    image: patrikjmelander/demo_bank:latest
    container_name: demo_bank
    ports:
      - 8080:8080
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      SPRING_DB_URL: jdbc:mysql://db:3307/lab1
      SPRING_JPA_HIBERNATE_DDL-AUTO: none
      SPRING_PROFILES_ACTIVE: prod
    depends_on:
      - db
